version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: cloud-assessment-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_password
      POSTGRES_DB: cloud_assessment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
